# Generated by Django 4.0.4 on 2022-05-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
